---
title: "LSOA_MCA"
format: docx
editor: visual
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r install, include=FALSE}

install.packages("soc.ca") 
install.packages("FactoMineR")
install.packages("factoextra")

install.packages("here") 
install.packages("haven") 
install.packages("sjlabelled")
```

```{r load, include=FALSE}

require(soc.ca)
require(here)
require(haven)
require(dplyr)
require(sjlabelled)
```

```{r data, include=FALSE}
data <- readRDS("C:/Users/Andre/OneDrive - Birkbeck, University of London/R/R_projects/Social_boundaries_LAC/Data/London/lsoa_data_sf.rds")

data <-  data %>% 
  dplyr::mutate(across(where(is.labelled), to_factor))

```

```{r wrangle}
# Function to factorize a numeric variable with relative breakpoints
factorize_numeric <- function(numeric_variable) {
  # Calculate the quantiles for breakpoints (0%, 33%, 66%, 100%)
  quantiles <- quantile(numeric_variable, probs = c(0, 1/3, 2/3, 1))
  
  # Convert to factor using relative breakpoints
  numeric_variable_fac <- cut(numeric_variable, 
                              breaks = quantiles, 
                              labels = c("Low", "Medium", "High"), 
                              include.lowest = TRUE)
  
  return(numeric_variable_fac)
}
# lone parent
data$household_composition_percent_couple_household_with_dependent_children_2011_fac <- factorize_numeric(data[[16]])

# unemployment
data$economic_activity_unemployment_rate_2011_fac <- factorize_numeric(data[[59]])

# foreigh born
data$country_of_birth_percent_not_united_kingdom_2011_fac <- factorize_numeric(data[[29]])


# Function to determine the highest proportion category
assign_category <- function(poor, average, good) {
  categories <- c("poor_access", "average_access", "good_access")
  proportions <- c(poor, average, good)
  return(categories[which.max(proportions)])
}

assign_category2 <- function(poor, average, good) {
  categories <- c("severe_limnitations", "little_limnitations", "no_limnitations")
  proportions <- c(poor, average, good)
  return(categories[which.max(proportions)])
}

assign_category3 <- function(...) {
  categories <- c("no_qualifications", "level_1_qualifications", "level_2_qualifications", "apprenticeship", "level_3_qualifications", "level_4_qualifications_and_above", "other_qualifications", "schoolchildren_and_full_time_students")
  proportions <- c(...)
  return(categories[which.max(proportions)])
}

# public_transport_accessibility
data$public_transport_accessibility <- mapply(assign_category, 
                                             data[,74], 
                                             data[,75], 
                                             data[,76]
                                             )

# health_day_to_day_activities
data$health_day_to_day_activities <- mapply(assign_category2, 
                                             data[,68], 
                                             data[,69], 
                                             data[,70]
                                            )
# Qualification level
data$highest_qualification <- mapply(assign_category3, 
                                     data[,60], 
                                     data[,61], 
                                     data[,62], 
                                     data[,63], 
                                     data[,64], 
                                     data[,65], 
                                     data[,66]
                                     )

```

```{r construction_MCA}
active <- data[,c(23:28,86:91)]
id <- data$LSOA11CD
sup <- data.frame(
  POPDEN = data$POPDEN,
  house_prices_median_price_2011 = data$house_prices_median_price_2011,
  household_income_2011_12_median_annual_household_income_estimate = data$household_income_2011_12_median_annual_household_income_estimate
)
```

```{r}
SOC.MCA <- soc.mca(active, sup, identifier = id, weight = data[5])

print(SOC.MCA)
```


```{r individuals}
# which.max(abs(SOC.MCA$coord))))))
map.ind(SOC.MCA,)
```


```{r}
data.sub <- subset(data, ID!= 1228)

active <- data.frame(data.sub[,2:19])
sup <- data.frame(data.sub$soctrust)

SOC.MCA.sub <- soc.mca(active, sup)
```

```{r}
map.ind(SOC.MCA.sub)
```


```{r}
(output.ind <- map.ind(SOC.MCA.sub
                      , point.alpha = 0.3
                      , point.fill = "whitesmoke"
                      , point.color = "black"
                      , point.size = 0.5) +
  ylim(-2,2) +
  xlim(-2,2)
 )
```
## Which categories are driving the axes?
```{r}
contribution(SOC.MCA.sub
             , dim = 1
             , all = FALSE
             , indices = FALSE
             , mode = "sort")
```

```{r}
(contribution1 <- map.ctr(SOC.MCA.sub
                         , dim = c(1,2)
                         , ctr.dim = 1
                         , point.shape = "variable"
                         , point.alpha = 0.8
                         , point.fill = "whitesmoke"
                         , point.color = "black"
                         , point.size = 0.2
                         , label = TRUE
                         , label.size = 1.8
                         , label.fill = NULL
                         , map.title = "1.dimension modalities"
                         , labelx = "default"
                         , labely = "default"
                         , legend = NULL) +
  ylim(-3,4) +
  xlim(-3,4) +
  theme(axix.text.x = element_text(size = 8, angle = 0),
         axix.text.y = element_text(size = 8, angle = 0),
         plot.title = element_text(size = 10, face = "bold")
         )
)
```

```{r}
(contribution2 <- map.ctr(SOC.MCA.sub
                         , dim = c(1,2)
                         , ctr.dim = 2
                         , point.shape = "variable"
                         , point.alpha = 0.8
                         , point.fill = "whitesmoke"
                         , point.color = "black"
                         , point.size = 0.2
                         , label = TRUE
                         , label.size = 1.8
                         , label.fill = NULL
                         , map.title = "2.dimension modalities"
                         , labelx = "default"
                         , labely = "default"
                         , legend = NULL) +
  ylim(-3,4) +
  xlim(-3,4) +
  theme(axix.text.x = element_text(size = 8, angle = 0),
         axix.text.y = element_text(size = 8, angle = 0),
         plot.title = element_text(size = 10, face = "bold")
         )
)
```
## Setting categories passive
```{r}
active <- data.frame(data.sub[,2:19]) 
sup <- data.frame(data.sub$soctrust)

options(passive = c("kindblue: Not heard of"
                    , "symph5: Not heard of" )
        ) 
## Dont forget to turn off

SOC.MCA.sub.passive <- soc.mca(active, sup)

SOC.MCA.sub.passive$names.passive

# options(passive = NULL)
```

# Supplementary categories

```{r}
#ind.explorer(SOC.MCA.sub.passive, active, sup)

(sup.p <- map.sup(SOC.MCA.sub.passive,
                 dim = c(1,2),
                 label.size = 2) +
                   
  ylim(-3,4) +
  xlim(-3,4) +
    
  theme(axix.text.x = element_text(size = 8, angle = 0),
         axix.text.y = element_text(size = 8, angle = 0),
         plot.title = element_text(size = 10, face = "bold"))
 
)

```

# Export results
```{r}
export(SOC.MCA.sub.passive, file = here("Output", "MCA_results.csv"))

```












```{r}

```







```{r}

```
